Repository githubschool/github-managers-brianamarie, pull requests merged in 2018-03, with the labels that each got.

#21 Ufi68/test1: Please add the very important md file lol ;)
  UFI68-20180313.md
Labels: suggestion

#25 Create bbahnemann-change_v01.md
  bbahnemann-change_v01.md
Labels: good first issue

#28 initial file for scampijoe_stuff, contains dinner recommends
  scampijoes_stuff1.md
Labels: suggestion

#29 Pease merge our useful file MA.md
  MA.md
Labels: enhancement

#30 Additions to the list
  briana-Rashmi.md
Labels: suggestion
